/*
******************************************************************************
Archivo:    	main.c
Info:     		Generated by Atollic TrueSTUDIO(R) 9.3.0   2020-05-30
Autor:			Joel Ermantraut
Ultima Mod.:	23/01/2020

NOTA: No olvidar que los ADCs de esta placa soportan hasta 3.3V.
******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include "stm32f4xx_gpio.h"
#include <stm32f4xx_adc.h>
#include "adc.h"
#include <stm32f4xx_rcc.h>
#include "CE_ADC_control.h"
#include "CE_GPIO_control.h"

/* Private macro */
/* Private variables */

ADC_PIN pote_adc = {
		GPIOC,
		GPIO_Pin_2,
		RCC_AHB1Periph_GPIOC,
		RCC_APB2Periph_ADC2,
		ADC2,
		ADC_InjectedChannel_1,
		ADC_Channel_12
};

Salida led1 = {
		RCC_AHB1Periph_GPIOD,
		GPIOD,
		GPIO_Pin_12,
		GPIO_PinSource12
};

/* Private function prototypes */

void delay(uint32_t tiempo);

/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
	CE_ADC_init(pote_adc);

	CE_conf_out(led1);

	int32_t adc_cuentas;

	while (1)
	{
		delay(100000);

		adc_cuentas = CE_ADC_read(pote_adc, 2);

		if (adc_cuentas < 2000) {
			CE_escribir_salida(led1, 0);
		} else {
			CE_escribir_salida(led1, 1);
		}

	}
}

void delay(uint32_t tiempo)
{

	while(--tiempo);

}
