/*
******************************************************************************
Archivo:     	main.c
Info:     		Generated by Atollic TrueSTUDIO(R) 9.3.0   2020-12-03
Autor:			Joel Ermantraut
Ult. Modif.:	06/01/2021

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include "CE_GPIO_control.h"

/* Private variables */

Salida led_bateria1 = {
		RCC_AHB1Periph_GPIOE,
		GPIOE,
		GPIO_Pin_7,
		GPIO_PinSource7
};
Salida led_bateria2 = {
		RCC_AHB1Periph_GPIOE,
		GPIOE,
		GPIO_Pin_8,
		GPIO_PinSource8
};
Salida led_bateria3 = {
		RCC_AHB1Periph_GPIOE,
		GPIOE,
		GPIO_Pin_9,
		GPIO_PinSource9
};

Salida puls_line_entrada_1 = {RCC_AHB1Periph_GPIOC, GPIOC, GPIO_Pin_9, GPIO_PinSource9};
Salida puls_line_entrada_2 = {RCC_AHB1Periph_GPIOA, GPIOA, GPIO_Pin_8, GPIO_PinSource8};
Entrada puls_line_entrada_3 = {RCC_AHB1Periph_GPIOC, GPIOC, GPIO_Pin_6};
Entrada puls_line_entrada_4 = {RCC_AHB1Periph_GPIOC, GPIOC, GPIO_Pin_8};

/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
	CE_conf_out(puls_line_entrada_1);
	CE_conf_out(puls_line_entrada_2);
	CE_conf_in(puls_line_entrada_3, GPIO_PuPd_DOWN);
	CE_conf_in(puls_line_entrada_4, GPIO_PuPd_DOWN);
	// Pines de entrada del keypad de pulsadores tactiles

    CE_conf_out(led_bateria1);
    CE_conf_out(led_bateria2);
    CE_conf_out(led_bateria3);
    // LEDs que marcan el estado actual de la bateria

	Salida salidas[2] = {
		puls_line_entrada_1,
		puls_line_entrada_2
    };
    Entrada entradas[4] = {
		puls_line_entrada_3,
		puls_line_entrada_4
    };

	while (1)
	{
		int boton = CE_matriz_presionado(entradas, salidas, 2);
		if (boton == NO_BUTTON) {
			CE_escribir_salida(led_bateria1, Bit_Low);
			CE_escribir_salida(led_bateria2, Bit_Low);
			CE_escribir_salida(led_bateria2, Bit_Low);
		} else {
			CE_escribir_salida(led_bateria1, Bit_High);
			CE_escribir_salida(led_bateria2, Bit_High);
			CE_escribir_salida(led_bateria2, Bit_High);
		}
	}
}
