/*
 * Archivo: 		main.c
 * Info: 			Generated by Atollic TrueSTUDIO(R) 9.3.0
 * Autor:			Joel Ermantraut
 * Ult. Mod.:		06/01/2021
 *
*/

#include "stm32f4xx.h"
#include "stm32f4xx_rcc.h"
#include "stm32f4xx_gpio.h"
#include "stm32f4xx_tim.h"
#include "CE_PWM_control.h"

void delay_ms(int n) { // Si n = 1000, 1 segundo
	void delay(uint32_t tiempo);

	do {
		delay(0x0fa0);
	} while(n--);
}

void delay(uint32_t tiempo)
{
	while(--tiempo);
}

PWM pwm = {
		RCC_APB1Periph_TIM4,
		8399,
		TIM4,
		TIM_OCMode_PWM2
};

Salida salida_pwm = {
		RCC_AHB1Periph_GPIOD,
		GPIOD,
		GPIO_Pin_12,
		GPIO_PinSource12
};

int main(void) {
    /* Initialize system */
    SystemInit();

    CE_PWM_init(salida_pwm, pwm);

    while (1) {
    	CE_PMW_change_duty(pwm, 100);
    	delay_ms(1000);
    	CE_PMW_change_duty(pwm, 50);
    	delay_ms(1000);
    	CE_PMW_change_duty(pwm, 0);
    	delay_ms(1000);
    }
}

